const allowedCommands = [
    'setup init',
    'setup reload',
    'network use',
    'network list',
    'wait',
    'account create',
    'account balance',
    'account list',
    'account import',
    'account clear',
    'account delete',
    'account view',
    'token create-from-file',
    'token create',
    'token associate',
    'token transfer',
    'topic create',
    'topic list',
    'topic message submit',
    'topic message find',
    'hbar transfer',
    'backup create',
    'backup restore',
    'record start',
    'record stop',
    'state download',
    'state view',
    'state clear',
    'script load',
    'script list',
    'script delete'
];

module.exports = allowedCommands;